version: "3.8"
services:
  server:
    build:
      context: .
    environment:
        NODE_ENV: production
        GOOGLE_APPLICATION_CREDENTIALS: /home/acuteangletech/xpensea-988cce69e3c6.json
    ports:
      - "3040:3040"

      
   

