version: "3.8"
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "3040:3040"
    volumes:
      - /home/acuteangletech/xpensea-988cce69e3c6.json:/usr/src/app/xpensea-988cce69e3c6.json
